import type { Product } from '@/types/product';

export const AFFILIATE_TAG = 'bricomaison-21';

export const mockProducts: Product[] = [
  // PERCEUSES (6)
  {
    asin: 'B08KGJXQZK',
    title: 'Bosch Professional GSB 18V-55 — Perceuse-Visseuse à Percussion sans fil 18V, 2 batteries 2.0Ah',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 149.99,
    currency: 'EUR',
    rating: 4.7,
    reviewCount: 2341,
    type: 'perceuse',
    brand: 'Bosch',
    affiliateUrl: 'https://www.amazon.fr/dp/B08KGJXQZK?tag=bricomaison-21',
    isPrime: true,
    badge: 'bestseller',
  },
  {
    asin: 'B07XVJNJRL',
    title: 'Makita DHP484RTJ — Perceuse à Percussion 18V Li-Ion 5.0Ah, Couple 54Nm, 13mm',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 199.00,
    currency: 'EUR',
    rating: 4.8,
    reviewCount: 1876,
    type: 'perceuse',
    brand: 'Makita',
    affiliateUrl: 'https://www.amazon.fr/dp/B07XVJNJRL?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B09LMZQP7R',
    title: 'DeWalt DCD778S2T-QW — Perceuse-Visseuse Compacte 18V XR, 2 batteries 1.5Ah, boîtier TSTAK',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 179.99,
    currency: 'EUR',
    rating: 4.6,
    reviewCount: 987,
    type: 'perceuse',
    brand: 'DeWalt',
    affiliateUrl: 'https://www.amazon.fr/dp/B09LMZQP7R?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07SNCN2HX',
    title: 'Black+Decker BDCDD12KB — Perceuse sans fil 12V MAX, batterie 1.5Ah, coffret',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 49.99,
    currency: 'EUR',
    rating: 4.1,
    reviewCount: 3456,
    type: 'perceuse',
    brand: 'Black&Decker',
    affiliateUrl: 'https://www.amazon.fr/dp/B07SNCN2HX?tag=bricomaison-21',
    isPrime: true,
    badge: 'rapport-qualite-prix',
  },
  {
    asin: 'B08CF4K19Y',
    title: 'Ryobi R18PD7-215S — Perceuse à Percussion 18V ONE+, 2 batteries 1.5Ah + 5.0Ah',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 129.00,
    currency: 'EUR',
    rating: 4.4,
    reviewCount: 654,
    type: 'perceuse',
    brand: 'Ryobi',
    affiliateUrl: 'https://www.amazon.fr/dp/B08CF4K19Y?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07WCMSJKH',
    title: 'Einhell TE-CD 18/48 Li — Perceuse-Visseuse sans fil 18V, couple max 48Nm, Power-X-Change',
    imageUrl: '/images/products/placeholder-perceuse.svg',
    price: 69.99,
    currency: 'EUR',
    rating: 3.9,
    reviewCount: 421,
    type: 'perceuse',
    brand: 'Einhell',
    affiliateUrl: 'https://www.amazon.fr/dp/B07WCMSJKH?tag=bricomaison-21',
    isPrime: false,
  },
  // VISSEUSES (5)
  {
    asin: 'B08MQPKRGZ',
    title: 'Bosch Professional GDX 18V-200 — Clé à Chocs sans fil 18V, couple 200Nm, 1 batterie 4.0Ah',
    imageUrl: '/images/products/placeholder-visseuse.svg',
    price: 189.00,
    currency: 'EUR',
    rating: 4.7,
    reviewCount: 1234,
    type: 'visseuse',
    brand: 'Bosch',
    affiliateUrl: 'https://www.amazon.fr/dp/B08MQPKRGZ?tag=bricomaison-21',
    isPrime: true,
    badge: 'coup-de-coeur',
  },
  {
    asin: 'B08PTSLGMK',
    title: 'Makita DTD155RTJ — Visseuse à Impact 18V, couple 165Nm, 2 batteries 5.0Ah, LXT',
    imageUrl: '/images/products/placeholder-visseuse.svg',
    price: 239.00,
    currency: 'EUR',
    rating: 4.9,
    reviewCount: 892,
    type: 'visseuse',
    brand: 'Makita',
    affiliateUrl: 'https://www.amazon.fr/dp/B08PTSLGMK?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07QF5GCMX',
    title: 'DeWalt DCF887D2T-QW — Visseuse à Impact 18V XR Brushless, couple 205Nm, 2x2.0Ah',
    imageUrl: '/images/products/placeholder-visseuse.svg',
    price: 219.99,
    currency: 'EUR',
    rating: 4.8,
    reviewCount: 1567,
    type: 'visseuse',
    brand: 'DeWalt',
    affiliateUrl: 'https://www.amazon.fr/dp/B07QF5GCMX?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07NTGXBWH',
    title: 'Ryobi ONE+ RID1801M — Visseuse à Impact 18V, couple 160Nm, sans batterie (vendu seul)',
    imageUrl: '/images/products/placeholder-visseuse.svg',
    price: 59.99,
    currency: 'EUR',
    rating: 4.2,
    reviewCount: 328,
    type: 'visseuse',
    brand: 'Ryobi',
    affiliateUrl: 'https://www.amazon.fr/dp/B07NTGXBWH?tag=bricomaison-21',
    isPrime: false,
  },
  {
    asin: 'B09XMFKTVZ',
    title: 'Metabo BS 18 LT BL Q — Perceuse-Visseuse sans fil 18V, couple 75Nm, moteur brushless',
    imageUrl: '/images/products/placeholder-visseuse.svg',
    price: 159.00,
    currency: 'EUR',
    rating: 4.5,
    reviewCount: 276,
    type: 'visseuse',
    brand: 'Metabo',
    affiliateUrl: 'https://www.amazon.fr/dp/B09XMFKTVZ?tag=bricomaison-21',
    isPrime: true,
  },
  // MEULEUSES (4)
  {
    asin: 'B07D3W3LBT',
    title: 'Bosch Professional GWS 18V-10 — Meuleuse Angulaire sans fil 18V, disque 125mm, 1x5.0Ah',
    imageUrl: '/images/products/placeholder-meuleuse.svg',
    price: 169.99,
    currency: 'EUR',
    rating: 4.6,
    reviewCount: 1102,
    type: 'meuleuse',
    brand: 'Bosch',
    affiliateUrl: 'https://www.amazon.fr/dp/B07D3W3LBT?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B08X7YBKQP',
    title: 'Makita DGA504RTJ — Meuleuse d\'Angle 18V LXT, disque 125mm, 2 batteries 5.0Ah',
    imageUrl: '/images/products/placeholder-meuleuse.svg',
    price: 279.00,
    currency: 'EUR',
    rating: 4.7,
    reviewCount: 743,
    type: 'meuleuse',
    brand: 'Makita',
    affiliateUrl: 'https://www.amazon.fr/dp/B08X7YBKQP?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07FPLMJNR',
    title: 'DeWalt DCG405NT-XJ — Meuleuse 18V XR Brushless 125mm, sans batterie, boîtier TSTAK',
    imageUrl: '/images/products/placeholder-meuleuse.svg',
    price: 149.00,
    currency: 'EUR',
    rating: 4.5,
    reviewCount: 489,
    type: 'meuleuse',
    brand: 'DeWalt',
    affiliateUrl: 'https://www.amazon.fr/dp/B07FPLMJNR?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B09KRTMWXY',
    title: 'Metabo WB 18 LTX BL 125 — Meuleuse Angulaire 18V Brushless, frein rapide, 125mm',
    imageUrl: '/images/products/placeholder-meuleuse.svg',
    price: 129.00,
    currency: 'EUR',
    rating: 4.3,
    reviewCount: 198,
    type: 'meuleuse',
    brand: 'Metabo',
    affiliateUrl: 'https://www.amazon.fr/dp/B09KRTMWXY?tag=bricomaison-21',
    isPrime: false,
    badge: 'rapport-qualite-prix',
  },
  // SCIES (3)
  {
    asin: 'B08NMPVGJK',
    title: 'Bosch Professional GST 18V-LI S — Scie Sauteuse sans fil 18V, course 26mm, 1x4.0Ah',
    imageUrl: '/images/products/placeholder-scie.svg',
    price: 159.00,
    currency: 'EUR',
    rating: 4.5,
    reviewCount: 612,
    type: 'scie',
    brand: 'Bosch',
    affiliateUrl: 'https://www.amazon.fr/dp/B08NMPVGJK?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B08QRPCXLM',
    title: 'Makita DJV182RT1J — Scie Sauteuse 18V LXT Brushless, course 28mm, 1 batterie 5.0Ah',
    imageUrl: '/images/products/placeholder-scie.svg',
    price: 249.00,
    currency: 'EUR',
    rating: 4.8,
    reviewCount: 334,
    type: 'scie',
    brand: 'Makita',
    affiliateUrl: 'https://www.amazon.fr/dp/B08QRPCXLM?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B07YBCL7XS',
    title: 'Ryobi ONE+ R18JS-0 — Scie Sauteuse 18V, course 26mm, sans batterie (vendu seul)',
    imageUrl: '/images/products/placeholder-scie.svg',
    price: 69.00,
    currency: 'EUR',
    rating: 4.0,
    reviewCount: 287,
    type: 'scie',
    brand: 'Ryobi',
    affiliateUrl: 'https://www.amazon.fr/dp/B07YBCL7XS?tag=bricomaison-21',
    isPrime: false,
  },
  // PONCEUSES (2)
  {
    asin: 'B08VMMJLKP',
    title: 'Bosch Professional GEX 18V-125 — Ponceuse Excentrique sans fil 18V, 125mm, 1x5.0Ah',
    imageUrl: '/images/products/placeholder-ponceuse.svg',
    price: 139.00,
    currency: 'EUR',
    rating: 4.6,
    reviewCount: 523,
    type: 'ponceuse',
    brand: 'Bosch',
    affiliateUrl: 'https://www.amazon.fr/dp/B08VMMJLKP?tag=bricomaison-21',
    isPrime: true,
  },
  {
    asin: 'B09LNWQZTR',
    title: 'Makita DBO180RT1J — Ponceuse Excentrique 18V LXT, 125mm, course 3mm, 1 batterie 5.0Ah',
    imageUrl: '/images/products/placeholder-ponceuse.svg',
    price: 219.00,
    currency: 'EUR',
    rating: 4.7,
    reviewCount: 412,
    type: 'ponceuse',
    brand: 'Makita',
    affiliateUrl: 'https://www.amazon.fr/dp/B09LNWQZTR?tag=bricomaison-21',
    isPrime: true,
  },
];
